using System;

namespace Bootstrap.Components.Configuration.Abstractions
{
    /// <summary>
    /// Final keys may be generated by runtime type, so we use a new type to present the information instead of using <see cref="OptionsAttribute"/> directly.
    /// </summary>
    public class OptionsDescriber
    {
        public string FilePath { get; set; }
        public string FileKey { get; set; }
        public string OptionsKey { get; set; }
        public Type OptionsType { get; set; }
    }
}