using System;

namespace Bootstrap.Components.Configuration.Abstractions
{
    /// <summary>
    /// Final keys may be generated by runtime type, so we use a new type to present the information instead of using <see cref="OptionsAttribute"/> directly.
    /// </summary>
    public class OptionsDescriber
    {
        public string FilePath { get; set; } = null!;
        public string FileKey { get; set; } = null!;
        public string OptionsKey { get; set; } = null!;
        public Type OptionsType { get; set; } = null!;
    }
}